language: node_js
node_js:
  - '8'
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - npm install
after_success:
  - npm run dist
  - cd dist ; for file in * ; do mv "$file" "${file// /-}" ; done ; cd ..
  - cd dist ; for file in * ; do mv "$file" "${file//shuttle./shuttle-}" ; done ; cd ..
  - cd dist ; for file in * ; do mv "$file" "${file//shuttle-/Shuttle-}" ; done ; cd ..
deploy:
  provider: releases
  api_key:
    secure: lPxxIUfX7zeJYo+igFsHS7qPCB0vZEuTT0Lcix45dls9JdhGWnDX6KgE9C3U53W5xbl+5iNnNw7vbe9XxbMXAp6RvTkVLzSZk0QDw4FYU2G9GeRdUsDmRLXi+oDjvsUdte5vjempV/lZ7e54HyNdTngo9KbQwsjkN+S0P6RRQ6YD3+LEfuOxZFXGcHWsWZuwNS7I4Zl2Cl4X+REZqOjhvc9iAax+yMABqwgpn0NppWmcvSK/gJ2X2GHFmvcNmmXlFDsXrhjXxLjgbBU6OfqGEBbz0VRXPv1Hdx+HOPv2SkfthGdTpmUI/7s2FjX56hTkNQFqA7xOlgb+qPx3Fcvy+vR4GJBqESDkqB8VGXdI2XCsBYIcwKYEtiplmTLG6ZFAtyQcw6qYFiOvDTtswoswPePPr0l0tZ/oo8td918p/0Wf2CjScV7oW9qf8qp2clzNWxYwjnnJzJpGbhcXOE5pVL7ofrWC62jz/wddlKqyE4gEQdcVJieSl/TnPp5SMR/sclmVQ3tXx+xzeikoyWOQ4nx0wuMuyytZ8D5N5J5WuGR/UfKJEzPw/kaoDuV9BMEgNNDjaDXDPHGtfsOCcVULjOIee0yP4Xwa7kO5aNFJfPry/7GvolvKJ7Mg0MdN/vxxjIcHoRYGQMutKEcfST9p/2y/Tf+WaiPXlE93hRr+KW4=
  skip_cleanup: true
  file_glob: true
  file:
    - "dist/latest.yml"
    - "dist/latest-mac.yml"
    - "dist/Shuttle*.exe"
    - "dist/Shuttle*.deb"
    - "dist/Shuttle*.zip"
    - "dist/Shuttle*.dmg"
    - "dist/Shuttle*.tar.gz"
  on:
    tags: true
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
