os:
- linux
- osx

language: node_js
node_js:
- '8'

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libc6-dev-i386
  gcc-multilib g++-multilib        ; fi

before_script:
- npm install

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build-mac         ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build-linux        ; fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cOGP2gnK2bUlslRfggOXNJdud5VTewsEYaDihqthmUOW7nHNEM06NOLJMo/luPASJgk/tk954TQPc99MBgBxQHw2LqgKcp6iAIqLTcsv727WDB1Eg9c/4jk0cskrqD7Z9OvJg66UjenmefQR9HZq1j47viZBBxnoGxTcSL7nzFM0kgtPrsxtaI/RccaPlcNjTrfjJ8D42onQM4Ex/m7Pbc2mx9SxA3AmBkN52wpwPdUGV+XwYuorgjSt+YgFdgb+k9BHwDEmLYo4TOp5nYg1CvlkQ1V8K+Ux192utYnL8sN3Q71qPhyEkwwAcjLT1FdIF2TI7cDl8kmakgYxSWlApjxNRPe9qoSRxBPIHLatkVqmb9vEC2x7gxZHTaCiP/DkywVhBbwRpp/jgIeF4MU+MiKhxFqEVlJG8+JfM1fy5DYCAptDq0HTAcRdCnXNyjoZnUcltiOUTUqm+GEFJz4sEZDFtFmBAdrLvDVom+AlE2B/4NYs3AYiLIjKXQxcayFJnYGgWgJr9FTU9a5jB1LN36K0P1vQdflDFZC6K8Cl88jQ+lYzYPp6v5bMOHYyDdq3Nk7kvjRz9vh6HDCcV0wFCCUetY4xYlgsCSgEK7ivdDns4UAQOLya+0Hty/8KJMAT8TgT6EP9EptlaPiJGzva1715VeGsdw4qIrxM8WC0Zns=
  file:
  - "dist/Shuttle-Linux-i386.AppImage"
  - "dist/Shuttle-Linux-x86_64.AppImage"
  - "dist/Shuttle-MacOS.dmg"
  - "dist/latest.yml"
  - "dist/latest-mac.yml"
  - "dist/latest-linux.yml"
  on:
    tags: true